apiVersion: v1
kind: Pod
metadata:
  name: starbucks-worker-pod
  namespace: default
  labels:
    name: starbucks-worker
spec:
  containers:
    - name: starbucks-worker
      image: rabbitmq:3-management
      imagePullPolicy: Always
      ports:
        - containerPort: 15672
          name: console
          protocol: TCP
        - containerPort: 4369
          name: nodes
          protocol: TCP
        - containerPort: 5672
          name: client
          protocol: TCP
      env:
        - name: MYSQL_HOST
          value: 10.73.0.3
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "cmpe172"
        - name: RABBIT_HOST
          value: 10.112.9.248
        - name: RABBIT_USER
          value: guest
        - name: RABBIT_PASSWORD
          value: guest
        - name: RABBIT_PORT
          value: "80"